# -*- coding: utf-8 -*-
"""Task1 Qualitative_FFT_LoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajAX2gquls5BOV_M1NNuHSjOX-tkqZBF

# Task 1 — MedQuAD QA
"""

!pip install -q datasets transformers accelerate peft evaluate rouge_score

import torch, gc, numpy as np, pandas as pd
from datasets import load_dataset, disable_caching
from transformers import AutoTokenizer, T5ForConditionalGeneration, TrainingArguments, Trainer, DataCollatorForSeq2Seq
from peft import LoraConfig, get_peft_model
import evaluate
import matplotlib.pyplot as plt

disable_caching()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""## Load + HARD filter invalid answers"""

raw = load_dataset("lavita/MedQuAD", split="train").shuffle(seed=42).select(range(4000))

def clean_text(x):
    if x is None:
        return ""
    if isinstance(x, (list, tuple)):
        x = " ".join([str(i) for i in x if i is not None])
    x = str(x).strip()
    # normalize
    if x.lower() in {"none", "null", "nan"}:
        return ""
    return x

def is_valid(example):
    q = clean_text(example.get("question"))
    a = clean_text(example.get("answer"))
    return (len(q) > 0) and (len(a) > 0)

filtered = raw.filter(is_valid)

print("Raw subset size:", len(raw))
print("Filtered valid QA size:", len(filtered))

train_test = filtered.train_test_split(test_size=0.2, seed=42)
test_valid = train_test["test"].train_test_split(test_size=0.5, seed=42)

train_dataset = train_test["train"]
val_dataset = test_valid["train"]
test_dataset = test_valid["test"]

print("Train/Val/Test:", len(train_dataset), len(val_dataset), len(test_dataset))

"""## Sanity checks"""

def count_invalid(ds):
    bad = 0
    for ex in ds:
        if len(clean_text(ex["answer"])) == 0:
            bad += 1
    return bad

print("Invalid answers in train:", count_invalid(train_dataset))
print("Invalid answers in val:", count_invalid(val_dataset))
print("Invalid answers in test:", count_invalid(test_dataset))

assert count_invalid(test_dataset) == 0, "Test still has invalid answers — filtering failed!"

"""## Tokenizer + preprocessing"""

model_name = "t5-base"   # if you hit OOM, change to "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)

MAX_SOURCE_LEN = 128
MAX_TARGET_LEN = 128

def preprocess_function(examples):
    questions = [clean_text(q) for q in examples["question"]]
    answers   = [clean_text(a) for a in examples["answer"]]

    inputs = ["question: " + q for q in questions]
    model_inputs = tokenizer(inputs, max_length=MAX_SOURCE_LEN, truncation=True)

    labels = tokenizer(text_target=answers, max_length=MAX_TARGET_LEN, truncation=True)
    label_ids = labels["input_ids"]
    label_ids = [[(t if t != tokenizer.pad_token_id else -100) for t in seq] for seq in label_ids]
    model_inputs["labels"] = label_ids
    return model_inputs

train_tokenized = train_dataset.map(preprocess_function, batched=True, remove_columns=train_dataset.column_names)
val_tokenized   = val_dataset.map(preprocess_function, batched=True, remove_columns=val_dataset.column_names)
test_tokenized  = test_dataset.map(preprocess_function, batched=True, remove_columns=test_dataset.column_names)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True)
rouge = evaluate.load("rouge")

GEN_KWARGS = dict(
    num_beams=4,
    max_new_tokens=220,
    early_stopping=True,
    no_repeat_ngram_size=3,
    repetition_penalty=1.15,
    length_penalty=1.0
)

def generate_text(model, question):
    inp = tokenizer("question: " + question, return_tensors="pt", truncation=True, max_length=MAX_SOURCE_LEN).to(device)
    with torch.no_grad():
        out = model.generate(**inp, **GEN_KWARGS)
    return tokenizer.decode(out[0], skip_special_tokens=True).strip()

"""## Manual ROUGE eval"""

def eval_rouge_manual(model, tokenized_ds, n=200):
    model.eval()
    subset = tokenized_ds.select(range(min(n, len(tokenized_ds))))
    preds, refs = [], []
    for ex in subset:
        input_ids = torch.tensor(ex["input_ids"]).unsqueeze(0).to(device)
        attn      = torch.tensor(ex["attention_mask"]).unsqueeze(0).to(device)

        with torch.no_grad():
            out = model.generate(
                input_ids=input_ids,
                attention_mask=attn,
                **GEN_KWARGS
            )

        pred = tokenizer.decode(out[0], skip_special_tokens=True).strip()
        ref_ids = [t for t in ex["labels"] if t != -100]
        ref = tokenizer.decode(ref_ids, skip_special_tokens=True).strip()

        preds.append(pred)
        refs.append(ref)

    res = rouge.compute(predictions=preds, references=refs)
    return {k: float(v) for k, v in res.items()}

"""## Baseline evaluation (no training)"""

torch.cuda.empty_cache(); gc.collect()
baseline_model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)

baseline_results = eval_rouge_manual(baseline_model, test_tokenized, n=200)
print("Baseline ROUGE:", baseline_results)

del baseline_model
torch.cuda.empty_cache(); gc.collect()

"""##  Full Fine-Tuning (FFT)"""

torch.cuda.empty_cache(); gc.collect()
fft_model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)

fft_args = TrainingArguments(
    output_dir="./t5_fft",
    eval_strategy="epoch",
    learning_rate=3e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=False,
    remove_unused_columns=True,
    report_to="none",
    logging_steps=50,
    save_strategy="epoch"
)

fft_trainer = Trainer(
    model=fft_model,
    args=fft_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator
)

fft_trainer.train()

fft_results = eval_rouge_manual(fft_model, test_tokenized, n=200)
print("FFT ROUGE:", fft_results)

"""##  LoRA (PEFT)"""

torch.cuda.empty_cache(); gc.collect()

base_model = T5ForConditionalGeneration.from_pretrained(model_name)
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q", "v"]
)
peft_model = get_peft_model(base_model, lora_config).to(device)
peft_model.print_trainable_parameters()

lora_args = TrainingArguments(
    output_dir="./t5_lora",
    eval_strategy="epoch",
    learning_rate=3e-4,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    fp16=False,
    remove_unused_columns=True,
    report_to="none",
    logging_steps=50,
    save_strategy="epoch"
)

lora_trainer = Trainer(
    model=peft_model,
    args=lora_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator
)

lora_trainer.train()

lora_results = eval_rouge_manual(peft_model, test_tokenized, n=200)
print("LoRA ROUGE:", lora_results)

"""## Plot ROUGE comparison"""

df = pd.DataFrame({
    "Baseline": baseline_results,
    "FFT": fft_results,
    "LoRA": lora_results
}).loc[["rouge1","rouge2","rougeL"]]

display(df)

df.T.plot(kind="bar")
plt.title("ROUGE Comparison (Filtered MedQuAD: valid answers only)")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.grid(axis="y")
plt.show()

"""##  Loss curves"""

def plot_loss(trainer, title):
    logs = pd.DataFrame(trainer.state.log_history)
    if "loss" not in logs.columns:
        print(title, ": no loss logs")
        return
    loss = logs[logs["loss"].notna()]
    if len(loss) == 0:
        print(title, ": no loss values")
        return
    plt.figure()
    plt.plot(loss["step"], loss["loss"])
    plt.title(title)
    plt.xlabel("Step")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()

plot_loss(fft_trainer, "FFT Training Loss")
plot_loss(lora_trainer, "LoRA Training Loss")

"""## Accurate qualitative analysis

"""

def qualitative_block(num_examples=3):
    # Sample ONLY from filtered test_dataset with real answers
    samples = test_dataset.shuffle(seed=7).select(range(min(num_examples, len(test_dataset))))

    # Reload baseline for comparison (FFT & LoRA are in memory)
    base = T5ForConditionalGeneration.from_pretrained(model_name).to(device)
    base.eval()

    for i, ex in enumerate(samples):
        q = clean_text(ex["question"])
        ref = clean_text(ex["answer"])

        print("\n" + "="*95)
        print(f"Question {i+1}: {q}")
        print("\nReference Answer:\n", ref)

        print("\nBaseline Output:\n", generate_text(base, q))
        print("\nFFT Output:\n", generate_text(fft_model, q))
        print("\nLoRA Output:\n", generate_text(peft_model, q))

    del base
    torch.cuda.empty_cache(); gc.collect()

qualitative_block(num_examples=5)